# Generated by Django 3.1.1 on 2020-09-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='short_link',
            new_name='short_link_hash',
        ),
    ]
