# Generated by Django 3.1.1 on 2020-09-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200921_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='full_link',
            field=models.CharField(max_length=2048),
        ),
    ]
